### ISSUE TITLE
As a data developer I want to run ETL processes in parallel so that I can complete jobs more quickly

### ISSUE THREAD

**Issue by saran-ahluwalia** [usds/justice40-tool#1038]
(Updated 2/8:)

All ETL classes can be run independently; none have any dependencies on each other. When we run application.py etl-run with no dataset specified, it downloads every dataset in DATASET_LIST from data/data-pipeline/data_pipeline/etl/constants.py.

We could add a very simple parallelization to etl-run to run all the items in DATASET_LIST in parallel. Most of the time is spent on I/O for these ETLs, waiting for the data to download and then writing the results to disk.

This would be fairly straightforward to setup a parallelization pool to run them independently. However, right now, each ETL uses the same `TMP` directory and then deletes all the files in the `TMP` directory at the end of the run. Run concurrently, this means sometimes deleting data needed by one of the other ETLs. To get around this, it would be easy to namespace the `TMP` directories using either the name of the class or a hash or something.

**Comment by lucasmbrown-usds** [comment]
Thanks for creating this. It's close but not quite. 

Some more details: 

All ETL classes can be run independently; none have any dependencies on each other. When we run `application.py etl-run` with no dataset specified, it downloads every dataset in `DATASET_LIST` from `data/data-pipeline/data_pipeline/etl/constants.py`. 

We could add a very simple parallelization to `etl-run` to run all the items in `DATASET_LIST` in parallel. Most of the time is spent on I/O for these ETLs, waiting for the data to download and then writing the results to disk. 

Score must be run after all of the ETLs are complete. Right now this process generates several scores (Score A, Score B, ... Score L) and these could potentially be run in parallel but this would take a little extra effort to recombine the results (since they're all currently written to self.df). We would need to double-check that none of the scores depend on a previous score, too.

**Comment by saran-ahluwalia** [comment]
@lucasmbrown-usds Understood, I think I have an idea of how to approach this and will open a draft PR.

Just to confirm, we would like to parallelize all instances we should scope this issue to the ETL first and validate that this provides performance improvements in IO-bound tasks.

It would be more opportune to then explore scoring all datasets in parallel. What are your thoughts on splitting this issue into two? One for ETL and one for scoring?

**Comment by sverchdotgov** [comment]
I kind of went on a tangent in https://github.com/usds/justice40-tool/pull/1039#pullrequestreview-830528432 as part of trying to understand the pipeline. Meeting with @saran-ahluwalia tomorrow about the PR, and I'm thinking there might be some other unrelated perf issues to file.

Since those issues don't exist yet, putting my notes here to not lose them. I found this: https://serverfault.com/questions/679989/most-efficient-way-to-batch-delete-s3-files Apparently `aws s3 rm --recursive` is extremely slow, which the tile deploy step uses (and the deploy step takes 30 minutes). I also found https://github.com/mediamonks/s3-batch-upload, no idea how good it is.
