### ISSUE TITLE
As a data developer, I want to have only one `tmp` directory for tests so that it's easier to diagnose test failures.

### ISSUE THREAD

**Issue by lucasmbrown-usds** [usds/justice40-tool#1092]
**Description**
As pointed out by @widal001 [here](https://github.com/usds/justice40-tool/pull/1088#pullrequestreview-841676632): 

> This is a bit outside the scope of the changes introduced by this PR, but something I flagged when submitting the first test suite for the NRI class is that the two different conftest.py (the one in data_pipeline/tests/ and the one in data_pipeline/ETL/tests/) actually write tmp files to different directories. As a result, depending on which subset of the tests we're running, the location of the temp files created by tests can change. This doesn't result in any failures but can make it confusing if you're trying to manually inspect the output after executing the tests. I can explain why this is happening if it would be helpful, though it might be easier to explain in real-time instead of asynchronously.

We should standardize on one directory for consistency. 

cc @esfoobar-usds

**Comment by widal001** [comment]
@lucasmbrown-usds @esfoobar-usds @saran-ahluwalia  This should be fairly easy to tackle, and I don't believe it's a blocking issue, so I'd be happy to take this on. 

A quick summary of what's happening here is that the following lines in [`data_pipeline/tests/conftest.py`](https://github.com/usds/justice40-tool/blob/a4137fdc9891de1012855fdd64fc2a7163c203d9/data/data-pipeline/data_pipeline/tests/conftest.py#L10) set the temp directory folder to `data_pipeline/data/tmp/tests/`
```python
@pytest.fixture(scope="session")
def mock_paths(tmp_path_factory) -> tuple:
    """Creates new DATA_PATH and TMP_PATH that point to a temporary local
    file structure that can be used to mock data folder during testing
    """
    # sets location of the temp directory inside the national_risk_index folder
    os.environ["PYTEST_DEBUG_TEMPROOT"] = str(TMP_DIR)
    TMP_DIR.mkdir(parents=True, exist_ok=True)
    # creates DATA_PATH and TMP_PATH directories in temp directory
    data_path = tmp_path_factory.mktemp("data", numbered=False)
    tmp_path = data_path / "tmp"
    tmp_path.mkdir()
    return data_path, tmp_path
```

While the following lines in [`data_pipeline/etl/score/tests/conftest.py`](https://github.com/usds/justice40-tool/blob/a4137fdc9891de1012855fdd64fc2a7163c203d9/data/data-pipeline/data_pipeline/etl/score/tests/conftest.py#L16) set the temp directory folder to `data_pipeline/etl/score/tests/temp_dir/`
```python
@pytest.fixture(scope="session")
def root(tmp_path_factory):
    basetemp = Path.cwd() / "temp_dir"
    os.environ["PYTEST_DEBUG_TEMPROOT"] = str(
        basetemp
    )  # this sets the location of the temp directory inside the project folder
    basetemp.mkdir(parents=True, exist_ok=True)
    root = tmp_path_factory.mktemp("root", numbered=False)
    return root
```

To address this discrepancy we have one of two options (both of which should be fairly straightforward:

1. **Recommended** Move the tests in `data_pipeline/etl/score/` to a new `score/` sub-directory inside the directory with the other etl tests: `data_pipeline/tests/` so that all tests are located in the same location and can share a common `conftest.py` file. Then update the score tests to use the `mock_paths` fixture that the ETL source tests use.
2. **Faster** Keep the tests in their current directory, but update the `basetemp` location to point to the same directory that is set in `data_pipeline/tests/conftest.py`

Do you all have a preference for which of the above strategies I use to address this issue?
