### ISSUE TITLE
Compare CEJST list of disadvantaged census tracts to DOT's lists and identify overlapping and non-overlapping census tracts

### ISSUE THREAD

**Issue by BethMattern** [usds/justice40-tool#1097]
The DOT has developed its own formula for identifying disadvantaged communities. We would like to compare their list of census tracts to the list of census tracts identified by the CEJST to identify:
1. Which census tracts are in both lists
2. How many and % census tracts are in both lists
3. Which census tracts are not in the CEJST list but are in the DOT list
4. How many and % census tracts are not in the CEJST list but are in the DOT list
5. Which census tracts are in the CEJST list but are not in the DOT list
6. How many and % census tracts are in the CEJST list but are not in the DOT list

This analysis should be done for 2 DOT lists:
SumIndicators3 - this is a list of prioritized census tracts that meet 3 thresholds identified by DOT
SumIndicators4 - this is a list of prioritized census tracts that meet 4 thresholds identified by DOT

Ideally, the output will be in excel so further analysis can be done.

**Comment by BethMattern** [comment]
[https://app.zenhub.com/files/358242767/126416ca-eb3a-45c0-acd5-70e37e595224/download](https://app.zenhub.com/files/358242767/126416ca-eb3a-45c0-acd5-70e37e595224/download)

**Comment by BethMattern** [comment]
[https://app.zenhub.com/files/358242767/fb79164d-2f89-44c5-bff2-a43bc9337b48/download](https://app.zenhub.com/files/358242767/fb79164d-2f89-44c5-bff2-a43bc9337b48/download)

**Comment by saran-ahluwalia** [comment]
Quoting Lucas:

1. “I am assuming we don’t care about the individual program itemizations” – i think we actually do care about getting that data out and clean at the level of the individual program.


2. imputing null data as zeroes seems rather dangerous here, right? wouldn’t that throw off our statistics in a way that doesn’t reflect that the data is just missing?


3. we’re interested in investments just as much (if not more than) benefits, if you’re interested in adding that calculation. the median and mean values of benefits are kind of interesting, but i think even more interesting would  be summing up all money (not benefits) invested in DACs across programs and dividing it by all money invested anywhere. the median/mean won’t account for the fact that one program may be 100x larger than another (it will treat both of those programs equally), whereas summing funding does.

4. what was your intention with the agency-specific files? right now most of them are just like a 10 x 30 matrix of zeroes. did you intend to have the program name as a column? otherwise i’m not sure how much these files make sense.

**Comment by saran-ahluwalia** [comment]
Answers to these questions can be found [here](https://github.com/usds/justice40-analysis/blob/main/dot_score_L_comparison_01072022/Issue_1097_cjest_sumindicators_four_three_comprehensive_01072022.ipynb).
