### ISSUE TITLE
Download Packet: Column width and tract order

### ISSUE THREAD

**Issue by esfoobar-usds** [usds/justice40-tool#1161]

**Comment by KameronKerger** [comment]
my QA (sorry for the delay) <- not sorry for the rhyme! 
GEOID10_TRACT should be Census tract ID
Can the alignment of all the fields be consistent? right / left/or middle (can we pick one? @emma-nechamkin or @lucasmbrown-usds who look at data a lot what do you think?
Can we change "Total threshold criteria exceeded" to "Total number of at or above thresholds criteria" so it is consistent with the site content?
Can we change low college attendance to high college enrollment? I'll bring this up during score M discussions today but "attendance" makes it seem like people aren't going to school...
I think the FEMA data is just "NationalRisk Index" and not "Natural Hazards Risk Index"
We should spell out the Superfund acronym since we do the others. it's National Priorities List
For asthma we can probably remove "Current" so it just starts with "Asthma"
Same for "Diagnosed diabetes" so just "Diabetes" (this will make it more consistent with the site
Overall can we make the columns a little smaller? Do if it is at like 40 make it more of a 30
I know this is still a todo but separating out the territories into their own tab on excel
Last, the pdf is still not in the download package (don't know if this is as expected or not.
Thank you!

**Comment by esfoobar-usds** [comment]
Moved @KameronKerger's feedback above to a new ticket #1215
