### ISSUE TITLE
Spike - propose .csv field names and specs

### ISSUE THREAD

**Issue by BethMattern** [usds/justice40-tool#1254]
Emma will think about the field names for the .csv that will be most helpful for data experts, as the main consumer of the .csv file.

**Comment by KameronKerger** [comment]
can you also think about how to best handle the territories @emma-nechamkin? in excel we are having them on separate tabs but in the csv my understanding is that there will be a bunch of blank fields and then the territories. if this is as expected, great, but if there is something better, great(er).

**Comment by emma-nechamkin** [comment]
In advance of the YAML for downloadable assets, I thought I'd put a little bit of thought in here as to what would be useful generally (in my opinion). 

I think, at a high-level, it would be nice to know a few things about each column:
- Source dataset?
- Is it used in the score?
- Is it normalized or subset in any way?

I would imagine, in a perfect world, a column name would be something like "source__short_desc__normalized". 

In addition, spaces in column names are tricky for a lot of statistical software. In addition, many programs (like STATA) will truncate column names for being too long. So -- my goal here is not to capture the full meaning of the variable, but enough of a hint that a user could reasonably remember what is going on after looking at a codebook a few times -- and can use the columns more easily in a variety of statistical languages. (An aside -- especially if we want this to be super accessible, the spaces in the csv have to go). 

## Variables from datasets

We have 21 datasets right now that get used in our pipeline (for now, I'm ignoring the comparison tool additions that are strictly regional). I would propose the following source names. Note that the point ISN'T to exhaustively spell out what the dataset is, but to provide a quick hint to the user. 

- `cdc_life_expectancy`: `cdc_le`
- `cdc_places`: `cdc_places`
- `cdc_svi_index`: `cdc_svi`
- `cencus_acs_2010`: `acs10`
- `census_acs_2019: `acs19`				
- `census_acs_median_income_2019`: `acs_mi19`		
- `census_decennial_2010`: `census10`			
- `child_opportunity_index`: `coi`
- `doe_energy_burden`: `doe_burd`
- `national_risk_index_2020`: `fema_nri`
- `ejscreen_2019`: `ejscreen`
- `persistent_poverty`: `per_pov`
- `tree_equity_score`: `tree`
- `epa_rsei`: `epa_rsei`			
- `geocorr`: `geocorr`			
- `housing_and_transportation_index`: `hous_trans_ix`			
- `hud_housing`:  `hud_chas`				
- `hud_recap`: `hud_recap`

The next component would be a *super short* reference to the variable contained. Here are some examples:

- `"Percent of individuals below 200% Federal Poverty Line"`: `poverty_200fpl`
-  `"Percent of individuals < 150% Federal Poverty Line"`: `poverty_150fpl`
- `"Median household income (State; 2019 inflation-adjusted dollars)"`: `state_med_income`
- `"Median household income in the past 12 months"`: `med_income`
- `"Area Median Income (State or metropolitan)"`: `ami`
- `"Percent enrollment in college or graduate school"`: `pct_high_ed`
- `"FEMA Risk Index Expected Annual Loss Score"` :`fema_risk`
- `"Expected building loss rate (Natural Hazards Risk Index)"`: `build_loss_rate`
- `"Expected agricultural loss rate (Natural Hazards Risk Index)"`: `ag_loss_rate`
- `"Expected population loss rate (Natural Hazards Risk Index)"`: `pop_loss_rate`

Then, we would include suffixes, like:
- for percentiles, `pctl`
- for min-max norm, `min-max`
- for urban / rural, `urb`, `rur`

This would hold for all of the variables that come from a single source. So, to make this super clear, we might have variable names like this for NRI:
- `fema_nri__ag_loss_rate__pctl`
- `fema_nri__ag_loss_rate__rur__pctl`

One note here is that I personally don't really like the way `__` looks BUT using a `__` allows people who access columns without string literals to do so neatly (e.g., `df.fema_nri__ag_loss_rate__pctl` or `df$fema_nri__ag_loss_rate__pctl`). I personally prefer using `.` instead of `__`, but I think `__` is better practice?

## Variables used in the score

Right now, our score variables are very long. I think we should make it a little clearer as: `score__category__factor`. We'd have something like:

### Booleans for the score 
Here I use 1 for the score, but we'd have whatever naming convention we are using
- "Definition M (communities)": `score1__dac`
- "Climate Factor (Definition M)": `score1__climate`

For the super long form ones and their components, we'd use similar stems so you could trace what was contributing. The idea of tagging everything with "score" is that it would help show what is actually being used by the scoring algorithm (vs the extras).
- "Greater than or equal to the 90th percentile for traffic proximity, is low income, and has low higher ed enrollment?": `score1__traffic__lowinc__lowhe`
- "Greater than or equal to the 90th percentile for traffic proximity?": `score1__traffic`
- "Is low income?": `score1__lowinc`

For island areas, we could add the suffix: `islnd` to each variable. 

I'll wait until the YAML file is done, but this was (at a high-level) what I was thinking. 

(PS Kameron -- For the csv, if we are working under the assumption that data people will look at the csv, I think it's completely fine to have lots of nulls for the islands, ESPECIALLY if we include a codebook that translates the short names to the downloadable name AND include a note about the islands in the codebook).

**Comment by vim-usds** [comment]
I also in agreement with this. In regards to my experience of connecting backend signals to the frontend, it seems that renaming these backend signals to follow a standard naming convention could be helpful. :)
