### ISSUE TITLE
Change base map color for airports because the current blue is too close to our DAC overlay

### ISSUE THREAD

**Issue by BethMattern** [usds/justice40-tool#1255]
Change base map color for airports because the current blue is too close to our DAC overlay

**Comment by BethMattern** [comment]
@glennettec can you provide some color recommendations?

**Comment by glennettec** [comment]
@vim-usds i compared our map to Google maps to see how they handle airports. i found that airports have the same base color as the surrounding area. 

i reviewed the options on Mapbox and found that we can remove the color from airports so that they show up the same color as the base map. 

"Not every component color property has to be included in the color palette. If a component color property is not included in the color palette (no color is assigned), it will fall back to the color defined for the Base component color property, which can’t be removed. This means you will always have a well-coordinated palette without needing to choose a value for every possible component color property." 
https://docs.mapbox.com/studio-manual/reference/styles/#colors
https://docs.mapbox.com/studio-manual/assets/reference-styles-components-color-palette-4f1556f610f025e85e0c813b2481fd93.mp4

We have two choices. Remove the color property for airports so that it can revert to the base map color. Or, find another color to use. 

My preference is to remove the color property.

**Comment by vim-usds** [comment]
@glennettec - this is great! I can look into removing the color for the airport

**Comment by katherinedm-usds** [comment]
when fixed @katherinedm-usds needs to respond to person from Regional Air Protection Agency that it's been fixed
