### ISSUE TITLE
As a data developer, I want to replace our custom data snapshots approach with `pytest-snapshot`

### ISSUE THREAD

**Issue by lucasmbrown-usds** [usds/justice40-tool#1263]
**Description**
https://pypi.org/project/pytest-snapshot/ provides a better solution than our home-grown snapshot tests because it does not require as much additional custom logic (because you can simple wrap the assertion as well as the snapshot writing into a single line). We should look into updating this custom logic to use this framework. 

At the same time, some of our custom tests use fixtures as the *inputs* to the test, not the outputs, and `pytest-snapshot` may not be as well suited for that. 

Investigate the pros and cons of the upgrade and implement the desired approach before we roll out unit testing to the other sources as part of #1217.

**Comment by lucasmbrown-usds** [comment]
Just do for NRI for now.

**Comment by widal001** [comment]
@emma-nechamkin and I were thinking about using this issue to serve as a scratch pad for our evaluation of `pytest-snapshot` to see if it meets the needs currently addressed by [`TestETL.test_update_test_fixtures()`](https://github.com/usds/justice40-tool/blob/521c61dff307212a91ad225bb5a32c9e88548746/data/data-pipeline/data_pipeline/tests/sources/example/test_etl.py#L504). If those needs are met, it may also require some refactoring of the tests overall to adapt them to use `pytest-snapshot`

Below I've outlined my current understanding of the current use case and highlighted some key questions we'll want to answer about `pytest-snapshot` that may inform if/how we use it to replace the current snapshot update mechanism:

### Use Case

Our use case for updating test fixtures has the following characteristics/needs:

- **Manual Updates of Input Data:** I want to manually create/edit an input file that mocks the data source for a particular datasource, so that I have control over the seed data that populates the snapshots created at each step of the ETL process I'm testing
- **Sequential Updates of Snapshots**: When I need to change the fixtures, I want to automatically update each snapshot in the ETL process using the output of the previous step as the input to the subsequent step (and the manually supplied input for the first step), so that I can trust the changes to the input will propagate across steps and I don't have to manually provide input data for each step. 
- **Explicit Execution:** I _don't_ want ETL snapshots to be updated unless I explicitly pass a certain flag to `pytest` via the CLI during the execution of tests, so that I don't accidentally update snapshots when I run the tests to validate the ETL outputs against those snapshots.
- **Isolated Execution:** I want to be able to update the snapshots for a single source while leaving the other snapshots unchanged, so that I don't accidentally update the snapshots for multiple ETL classes when I'm only trying to update one.
- **Separation of Testing Logic (Potentially):** I want to be able to separate the code/logic used to test the output of my ETL process from the code/logic used to update my snapshots, so that I can validate additional conditions about the output of the ETL process beyond whether or not it matches the most recently updated snapshot.

**Comment by widal001** [comment]
### Research Questions

Some questions we'll need to answer about `pytest-snapshots` in order to assess whether or not it satisfies the conditions outlined above include:

1. How does `pytest-snapshot` actually update snapshot files when `pytest --snapshot-update` is called from the CLI?
2. Can we limit the update of snapshots to individual directories or files? This is critical for the **Isolated Execution** criterion.
3. Can the snapshot of one test be used as the input to another snapshot test? This is the current behavior described by the **Sequential Updates of Snapshots** criterion.
3. Are there any limits to the types of files that `pytest --snapshot-update` can update? If so, which ones are supported and do we need to manage separate snapshot modifications for the unsupported file types?
4. Can `pytest-snapshot` be used to update test fixtures without having to build a snapshot test around each fixture we want updated? If not, does this require a broader refactor of our testing suite?

**Comment by emma-nechamkin** [comment]
Here are some answers! 

1. I think `--snapshot-update` does the following: (1) it deletes the existing snapshot, (2) it writes bytes of the snapshot. Here's the "file writing code": 
```        if self._snapshot_update:
            encoded_value = encode(value)
            if encoded_expected_value is None or encoded_value != encoded_expected_value:
                decoded_encoded_value = decode(encoded_value)
                if decoded_encoded_value != value:
                    raise ValueError("value is not supported by pytest-snapshot's serializer.")

                snapshot_path.parent.mkdir(parents=True, exist_ok=True)
                snapshot_path.write_bytes(encoded_value)
                if encoded_expected_value is None:
                    self._created_snapshots.append(snapshot_path)
                else:
                    self._updated_snapshots.append(snapshot_path)
```

2. In terms of snapshot updates, we can definitely do just a few directories (the package handles paths super nicely). I also think you can do `pytest::TEST --update-snapshots`. 
3. I think for this, we would have to first update the snapshot and then run the next test. As far as I can tell, sequential updating isn't possible. 
4. I think this will work for what we would want -- yaml or csv or something string based -- with the caveat that as far as I can tell, the code has snapshots in bytes. I *do not* think this is a problem for us. Here's the encoding/decoding function from the codebase: 
```    def _get_compare_encode_decode(self, value: Union[str, bytes]):
        """
        Returns a 3-tuple of a compare function, an encoding function, and a decoding function.

        * The compare function should compare the object to the value of its snapshot,
          raising an AssertionError with a useful error message if they are different.
        * The encoding function should encode the value into bytes for saving to a snapshot file.
        * The decoding function should decode bytes from a snapshot file into a object.
        """
        if isinstance(value, str):
            return _assert_equal, _file_encode, _file_decode
        elif isinstance(value, bytes):
            return _assert_equal, lambda x: x, lambda x: x
        else:
            raise TypeError('value must be str or bytes')
```
5. No, but I actually am not sure what the point of a fixture absent a test is? Like I'd think (personally) that a truncated CSV  might be more helpful than the snapshots, which are far less information? What am I missing here?

**Comment by emma-nechamkin** [comment]
So I guess my overall takeaway here is -- this isn't exactly the same as what we have implemented. I'm not sure if the drawbacks are significant enough, though,  to use something custom built vs. publicly-available. What do you think?
