### ISSUE TITLE
Add new wording to the map panel that appears upon load when no tract is selected

### ISSUE THREAD

**Issue by BethMattern** [usds/justice40-tool#1359]
Kameron has new wording & design for this area on the map.

**Comment by KameronKerger** [comment]
![percent](https://user-images.githubusercontent.com/77702996/156473691-1fc736b4-e5f1-434b-ac05-8f75ae3cb770.svg)
![percentile](https://user-images.githubusercontent.com/77702996/156473692-1fb0f094-72a8-4e1a-8273-be62c320ba47.svg)
![threshold](https://user-images.githubusercontent.com/77702996/156473694-55018fc2-d16c-4f45-8ec9-eea003e64470.svg)
![tracts](https://user-images.githubusercontent.com/77702996/156473696-d466b42b-f64b-4c54-83af-d8660199ddce.svg)
![side_panel_unselected](https://user-images.githubusercontent.com/77702996/156473803-8d5a0765-417f-448b-b705-95465d8e2b67.png)

**Comment by KameronKerger** [comment]
![side_panel_unselected](https://user-images.githubusercontent.com/77702996/156662942-2f319150-028e-4da3-ab25-404479c1d0d6.png)

**Comment by KameronKerger** [comment]
Things to know

This tool identifies communities that are marginalized, underserved, and overburdened by pollution. These communities will be at or above the thresholds for one or more of eight categories of criteria.

The tool uses census tracts that represent about 4000 people and are the smallest unit of geography at which consistent data is currently available.

The tool ranks each census tract using percentiles which show how much burden each tract has relative to all the other tracts. 

Percents are also used to show the share of people in the tract have certain socioeconomic characteristics. 

Thresholds for each data source determine IF each tract is identified as experiencing burdens disproportionally AND has those socioeconomic characteristics.

**Comment by KameronKerger** [comment]
[side_panel_not_selected_3_25.pdf](https://github.com/usds/justice40-tool/files/8353246/side_panel_not_selected_3_25.pdf)
Things to know
This tool identifies communities that are marginalized, underserved, and overburdened by pollution.  These communities are located in census tracts that are at or above the thresholds in one or more of eight categories of criteria.

The tool uses census tracts that represent about 4,000 people, which is the smallest unit of geography  for which consistent data can be displayed on the tool.

The tool ranks each census tract using percentiles that show how much burden each tract experiences relative to all other tracts, for each criteria.

Percentages are used for certain variables, i.e. those relating to high school achievement rate and to the share of individuals not currently enrolled in higher education.

Thresholds for each category determine if a tract should be identified as disadvantaged because it has exceeded a certain value for the relevant indicators.
