### ISSUE TITLE
Make the count of thresholds exceeded on the side panel more clear

### ISSUE THREAD

**Issue by BethMattern** [usds/justice40-tool#1403]
Users seem confused by the count of thresholds exceeded, but this number is useful and we need to retain it.

- [x] Add 2 threshold lines
- [x] add no threshold case
- [x] update button color
- [x] add mail icons
- [x] update both exceed statements

**Comment by BethMattern** [comment]
@KameronKerger Lucas talked me out of changing the number of thresholds exceeded to number of categories. Now I can't even remember the problem we were trying to solve?

**Comment by KameronKerger** [comment]
I thought that might happen :) 
a couple of reasons, one, people are confused by the methodology. two, the math is weird because if you count them they don't match the number. three, individual thresholds don't really "matter" and it is creating a false narrative when you have like 10 indicators exceeded but still aren't identified. and lastly, Emma puts this better than I can but it is something like the individual indicators aren't that important mathematically and a better representation of "cumulative impact" is actually at the category levels, tracts that exceed in more categories is more of an indicator of disproportionate impact.

**Comment by KameronKerger** [comment]
outcome of the thresholds / burdens / combined meeting @vim-usds 
note the inclusion of the # of categories and the removal of the total number of thresholds
![Screen Shot 2022-03-18 at 11.24.13 AM.png](https://images.zenhubusercontent.com/60a81149dee122a5d67208e5/e452a829-90ce-451a-b5ce-094dee49f5b3)

**Comment by KameronKerger** [comment]
![side_panel_update_3_18.png](https://images.zenhubusercontent.com/60a81149dee122a5d67208e5/9006007b-fdd5-4ee5-8acd-36f482489175)

@KameronKerger to add no case to this ticket.

**Comment by KameronKerger** [comment]
adding the no state for clarity
![new_panel_no_3_23.png](https://images.zenhubusercontent.com/60a81149dee122a5d67208e5/f0f9d994-75c0-4828-8aa2-e0ede6432909)
