### ISSUE TITLE
Higher ed threshold modification

### ISSUE THREAD

**Issue by emma-nechamkin** [usds/justice40-tool#1509]
- Right now, we see aberrations due to low shares of college students and high low income percentiles. If we want to remove students from contributing to income, we should explicitly do this. 
- The cutoff for college students should be better aligned to the share of students attending elite schools.

Our goal is to modify income in tracts that have under some high threshold of students (80% is my starting number!) so they can continue to be included. 

May require refinement going forward.

**Comment by emma-nechamkin** [comment]
This will involve two parts:

- Right now, we see aberrations due to low shares of college students and high low income percentiles. If we want to remove students from contributing to income, we should explicitly do this. 
- The cutoff for college students should be better aligned to the share of students attending elite schools.

Our goal is to modify income in tracts that have under some high threshold of students (80% is my starting number!) so they can continue to be included. 

May require refinement going forward.

**Comment by adwel81** [comment]
I agree with revisiting whether educational *enrollment* should be such a significant piece of the threshold criteria.

**Current enrollment is highly correlated with the age distribution -**- Areas with older populations tend to have lower enrollment.
Because of this Age relationship, there is an inverse relationship between current enrollment and attainment. On average, areas with lower current enrollment tend to have higher high school and college attainment

Below is analysis of all census tracts in New York state.

The first table is by Age quintile (using % over Age 65).
The second is by Higher Ed Enrollment quintile (from the CEJST data)

Therefore I don't think that low educational enrollment is a great measure of disadvantage - It seems to reflect the age distribution.
This has big implications for areas with lots of students who may not be permanent residents.

The map shows the Old North End of Burlington Vermont. This area has low income, many renters, poor housing quality, high linguistic isolation (thriving immigrant community), and poor health outcomes. However it fails to pass any of the thresholds because of high educational *enrollment*, due to high numbers of students attending local colleges. I would encourage reviewers to look at other lower-income, high-renter areas in student towns/cities.

![image](https://user-images.githubusercontent.com/10234487/163230232-89aa1fe5-39d1-4d07-aa42-9fe106c3cbfa.png)


![image](https://user-images.githubusercontent.com/10234487/163231443-03c361fd-20a5-4fbb-b37a-ee3e4ad59fa1.png)

**Comment by emma-nechamkin** [comment]
Closing because it appears the income imputation takes care of this

**Comment by emma-nechamkin** [comment]
also -- thank you so much for the super thoughtful analysis @adwel81!
