### ISSUE TITLE
Import tribal boundaries data so that we may be able to show on map / identify tracts that are in tribal boundaries

### ISSUE THREAD

**Issue by BethMattern** [usds/justice40-tool#1577]
Overlay tribal boundaries on the map so that users can see which tracts are a part of tribal lands.

Use Census BAS data - https://www.census.gov/geographies/mapping-files/2022/geo/bas/2022-bas-shapefiles.html

Emma will 
import the data & map to census tracts.
Add indicator to tracts

**Comment by emma-nechamkin** [comment]
All of these shapefiles are at the state level, with geometries only. Here are some details on file naming:

![Screen Shot 2022-04-26 at 2.38.33 PM.png](https://images.zenhubusercontent.com/61f0224dc73ca459249d1b5d/5da7f336-5211-40f5-a498-528537856c13)

Here is a technical guide: https://www2.census.gov/geo/pdfs/partnerships/bas/BAS_Technical_Guide.pdf

(Continuing to dig around)

**Comment by emma-nechamkin** [comment]
Pulling this down. Will confirm match. 

https://www.census.gov/programs-surveys/geography/technical-documentation/records-layout/2020-aiannh-record-layout.html#tract

**Comment by emma-nechamkin** [comment]
So, as an update -- for this, I'm actually pulling this file: https://www2.census.gov/geo/docs/maps-data/data/rel/centract_aia.txt

This is a straight CSV and uses 2010 tracts. Here's why I'm using it:

1. Since we use 2010 tracts, if we used the 2020 tract relationship file, we would have to make pretty significant assumptions (e.g., if 10% of tract A is AINNH and 30% of tract A maps to tract 2010_A, it seems like a big logical jump to assume 30% of the AINNH population is in tract 2010_A). 
2. Using the BAS shapefiles from 2020 seems like a pretty significant undertaking (it's 100s of files to download and digest) for something that functions as a temporary yardstick. 
3. My suggestion here: right now, visualize whether a tract contains any tribal area. Moving forward, add BAS as a map layer.

**Comment by emma-nechamkin** [comment]
TODO: Remove from score, keep as a boolean for visualization.

**Comment by emma-nechamkin** [comment]
![Screen Shot 2022-05-02 at 11.34.11 AM.png](https://images.zenhubusercontent.com/61f0224dc73ca459249d1b5d/5aab084a-9b0b-465d-91c2-d53931897b4b)

**Comment by emma-nechamkin** [comment]
(@BethMattern -- this requires a final data check on my end)
