### ISSUE TITLE
Write copy to explain change to higher education

### ISSUE THREAD

**Issue by BethMattern** [usds/justice40-tool#1675]
We need clear and concise copy that we can circulate for approval that describes the change to higher ed and incorporating it into low income

**Comment by KameronKerger** [comment]
honestly "people reporting low incomes, not including college students" works for me

**Comment by emma-nechamkin** [comment]
The CEJST 1.0 methodology no longer explicitly limits the share of the population within each census tract currently attending college or university. Instead, the tool assumes all college students are low income and removes them from the percent of the population identified as low income. The indicator thus represents the population not reporting low incomes, removing college students. This implicitly addresses tracts that appear low income simply because they have mostly college students without creating a strict and explicit threshold.

**Comment by KameronKerger** [comment]
need to figure out how to handle the fact that higher ed data is not available for two of the territories. we need to be able to explain that somewhere...
