### ISSUE TITLE
Write copy to explain methodology for imputing missing income and higher ed data

### ISSUE THREAD

**Issue by BethMattern** [usds/justice40-tool#1676]

**Comment by KameronKerger** [comment]
For tracts with missing income data, income is estimated based on an average of the incomes in the surrounding tracts.

**Comment by emma-nechamkin** [comment]
Clarification -- low income is the % of population living below 200% FPL. For tracts with missing income, low income is estimated based on an average of the percent of the population living below 200% FPL. 

as an aside -- you might wonder why we don't weight it based on population. This is because we don't know the extent of the overlap. If a tract is 99% surrounded by tract A, which has 10 people, and 1% covered by tract B, which has 100 people, should tract B be worth 10x tract A?

**Comment by KameronKerger** [comment]
@emma-nechamkin is there a way to say this that minimizes the need to understand math? can we remove the "of the percent" part and still have it be true?

**Comment by emma-nechamkin** [comment]
@KameronKerger i think so! but i do want to make clear that it's a measure of people, not of money
