### ISSUE TITLE
Geo utils follow up

### ISSUE THREAD

**Issue by emma-nechamkin** [usds/justice40-tool#1839]
@mattbowen-usds: I just realized the existence of `data_pipeline.etl.sources.geo_utils`. It looks like this was done in a prior PR. Was there a reason to put the functions there instead of adding these to `data_pipeline.utils`? Was there circular imports issues?

_Originally posted by @esfoobar-usds in https://github.com/usds/justice40-tool/pull/1828#discussion_r949321742_

I merged the donut hole code so we can have it in the narwhal release and opened this issue so we can modify as needed.

**Comment by mattbowen-usds** [comment]
The reasons were

1. Originally, they were purely for sources
2. They effectively (and actually, as written) depend on the census ETL, so it seemed like a lie to put them in data_pipeline.utils, since lower packages shouldn't really depend on the higher ones.

I could rewrite without the code dependency on `census.etl.CensusETL` and make running that manual --- it'll still logically have the dependency, but won't structurally at least. Open to feedback.

**Comment by mattbowen-usds** [comment]
We are not going to refactor this at this time. Closing.
