### ISSUE TITLE
Add USVI and Guam to territory shortcuts on map 

### ISSUE THREAD

**Issue by BethMattern** [usds/justice40-tool#1872]
Add shortcuts on the map for USVI and Guam since they are now included in 1.0.

For mobile, we should not display any shortcuts. So remove all territory shortcuts, 48, AK and HI and remove zoom icons.

**Comment by vim-usds** [comment]
Currently we have a BE Signal called `UI_EXP`, which stands for UI Experience.

This can have 1 of 3 values:

1. Nation
2. Puerto Rico
3. Island Areas

This BE signal will allow us to change what categories and indicators to show in the side panel.

### Nation
Show all categories

### Puerto Rico
If this BE signal is Puerto Rico we show the categories and indicators:

Energy 
- Energy cost, PM2.5

Housing
- Housing cost

Legacy Pollution
- Abandoned mines, FUDS, Haz Waste, SuperFunds, RMP

Workforce Dev
- Low med income, Unemploy, Poverty

### Island Areas (AS, GU, MP, VI)

Workforce Dev
- Low med income, Unemploy, Poverty

Assuming this is true unless I hear otherwise
