### ISSUE TITLE
Run a one-time check on count of federal Indian reservations

### ISSUE THREAD

**Issue by katherinedm-usds** [usds/justice40-tool#1917]
## Describe the task
We should do a one-time check on the BIA data we import, such that after import that have (for now in our staging environment) 326 federal Indian reservations on our map. The number 326 from https://www.bia.gov/faqs/what-federal-indian-reservation. 

If that one-time check to make sure we have all reservations fails, there's a [list](https://en.wikipedia.org/wiki/List_of_Indian_reservations_in_the_United_States) of federal Indian reservation names that we can use to track down which reservations  are not shown on our map and troubleshoot.

**Comment by vim-usds** [comment]
@mattbowen-usds are you available to work on this by any chance?

**Comment by mattbowen-usds** [comment]
@vim-usds sure, I'm happy to take it!

**Comment by vim-usds** [comment]
@mattbowen-usds - thank you!

**Comment by mattbowen-usds** [comment]
Here's BIA's own map of the tribal data: https://www.arcgis.com/home/webmap/viewer.html?url=https%3A%2F%2Fbiamaps.doi.gov%2Fserver%2Frest%2Fservices%2FDivLTR%2FBIA_AIAN_National_LAR%2FMapServer&source=sd

**Comment by mattbowen-usds** [comment]
I made an ipython notebook to do this check: https://github.com/usds/justice40-tool/blob/06631a38b695b9370cc858f1111e789ee1a9ba67/data/data-pipeline/data_pipeline/ipython/check_tribal_count.ipynb

We have 326 names tribal areas (335 if you look just at the names ,and then that drops to 326 if you remove parentheticals in names so that tribes like _ 'Acoma (Red Lake) LAR' and 'Acoma LAR'_ are counted as the same tribe.

**Comment by mattbowen-usds** [comment]
With the merge of #1919 this is done.
