### ISSUE TITLE
[SPIKE] As a developer, I want to understand the options for implementing various zoom levels for national data at the census block group level.

### ISSUE THREAD

**Issue by switzersc-usds** [usds/justice40-tool#196]
**Description**
We have a bunch of data to display at the census block group level that is easy to display at a relatively zoomed in level (eg zoom level 9); however, we want to display this as more zoomed out levels to give users an understanding of the data at a higher level. We'd love to have this conversation with the community to discover and understand options for implementing various zoom levels in terms of data, tiling, and UX design. 

**Solution**
TBD

**Describe alternatives you've considered**
TBD

**Links to user research or other resources**

**Tasks**

**Definition of "Done"**

**Comment by mikelmaron** [comment]
@switzersc-usds this is challenge I've been experimenting on within the [earthrise collaboration on Justice 40](https://earthrise-media.github.io/justice-map/). 

Because lower zoom tiles (between 1-9) will each cover more territory, by default the tiles will contain more features than tiles at higher zooms (9+), and then hit limits on MVT tile size (500kb), suffer performance hits, or have visible artifacts from dropping or over simplifying features. My approach has been to have different tiling strategies for low zoom vs high zoom tiles, with low zoom tiles having somewhat less detail but still giving a visually accurate understanding of the data. And then, in the style, gradually blend the low zoom and high zoom tiles together to smooth out the transition.

For the data preprocessing, the approach I took was to assign each block group's indicator value into 10 buckets, then dissolve neighbors by buckets. The result has significantly fewer features, that have no problem rendering at low zoom. The GeoJSON output is then processed into tiles. See [this notebook](https://github.com/earthrise-media/justice-map/blob/main/notebooks/bucket_d_pm25_2.ipynb) for details. 

For the front end styling, each layer's style is dynamically built from a configuration. A single indicator will have two fill layers -- one for high and one for low. The alpha of the fill layers are interpolated between zoom 9 and 11, with low zoom layers fading out, and high zoom layers fading in. Check out [the configuration](https://github.com/earthrise-media/justice-map/blob/main/lib/pmap.ts#L65-L194), and how the [style is built](https://github.com/earthrise-media/justice-map/blob/main/lib/pmap.ts#L22-L60).

If you find this approach helpful, let me know if you have any questions.

**Comment by NatHillardUSDS** [comment]
Thanks Mikel for weighing in! This is a very interesting approach. Would you be able to create a PR against our repo to bring this logic over? This project and repo would really benefit from your expertise in this area, as well as the findings you have already discovered. I can help provide any additional context on our implementation, though thus far it's quite simple and largely contained in [this file](https://github.com/usds/justice40-tool/blob/main/client/src/components/map.tsx). Happy to answer any questions though or provide any clarification. 

I should note that on main, we are currently using ol-mapbox-styles to get the benefit of expressions/contexts, as seen in [this file](https://github.com/usds/justice40-tool/blob/main/client/src/components/map.tsx), so the approach should be fairly transferrable. 

One issue we've come across though is that `interpolate` for `fill-color` appears to not work with mbtiles (see file attached to that other ticket) or mvt flat-files (as seen in our S3 at the url `http://usds-geoplatform-justice40-website.s3-website-us-east-1.amazonaws.com/nm/{z}/{x}/{y}.pbf`). Is this approach surmountable / would you be able to weigh in on this bug as well? Very similar code worked against a `pg_tileserv` db.  I initially assumed this was an issue with `ol-mapbox-style` but this appears to be an issue with vanilla mapbox as well - it's possible this is a simple syntax error? Any assistance you can provide with this would be appreciated as well!

**Comment by NatHillardUSDS** [comment]
(as a way to work around this, I temporarily took out OLMS and replaced with native OL styling on our demo branch [here](https://github.com/usds/justice40-tool/blob/nathillardusds/demo0617/client/src/components/map.tsx) - this is not ideal in that mapbox styling would be easier to work with overall; additionally, it would be easier to implement the approach you call out directly within mapbox styles as opposed to reimplementing within OpenLayers)

**Comment by mikelmaron** [comment]
@NatHillardUSDS addressed the styling bug in the other issue -- let me know if that addresses it or not. 

Regarding the tile strategy, I'm a bit short of bandwidth to set this up as a PR directly, but am happy to help you all figure this out. We could set up time to pair on a call if helpful.

**Comment by NatHillardUSDS** [comment]
Spinning off the data pipeline part of this to a new ticket [here](https://app.zenhub.com/workspaces/justice40-60993f6e05473d0010ec44e3/issues/usds/justice40-tool/209).

**Comment by NatHillardUSDS** [comment]
Thanks @mikelmaron ! I can try the frontend side of this locally, and then I can plan to reach out to discuss further / find a time to pair

**Comment by NatHillardUSDS** [comment]
Discussed approach further with Mikel yesterday, have a plan forward with the related data-side ticket
