### ISSUE TITLE
"Number of Tribal areas within Census tract” is blank for all entries in the download file on staging

### ISSUE THREAD

**Issue by vim-usds** [usds/justice40-tool#2062]
See here:

https://static-data-screeningtool.geoplatform.gov/data-versions/1.0/data/score/downloadable/1.0-communities.csv

**Comment by mattbowen-usds** [comment]
Well that's not supposed to happen. I'll spend an hour tomorrow to see if I can figure out why.

**Comment by mattbowen-usds** [comment]
This data point is showing up for me on local runs and showed up in the run merging narwhal into main, so I've rerun the 1.0 release action to see if maybe the branch I ran it on last had a defect that's since been resolved. If not, well, I'll have some really slow debugging to do I guess.

**Comment by mattbowen-usds** [comment]
Okay, I was looking at a file too early in the pipeline. We ended up only putting counts for Alaska, so the real field is named "Number of Tribal areas within Census tract for Alaska." The download was pulling from the old, defunct filed that is now all blank since we don't do national counts. I've updated the fieldname in the downloads accordingly (cc @KameronKerger and @katherinedm-usds ) and a PR will be coming shortly with the fix.

**Comment by KameronKerger** [comment]
Thank you so much @Matt ***@***.***>

From: Matt Bowen ***@***.***>
Reply-To: usds/justice40-tool ***@***.***>
Date: Wednesday, November 9, 2022 at 7:33 AM
To: usds/justice40-tool ***@***.***>
Cc: "Kerger, Kameron N. EOP/OMB" ***@***.***>, Mention ***@***.***>
Subject: Re: [usds/justice40-tool] "Number of Tribal areas within Census tract” is blank for all entries in the download file on staging (Issue #2062)


Okay, I was looking at a file too early in the pipeline. We ended up only putting counts for Alaska, so the real field is named "Number of Tribal areas within Census tract for Alaska." The download was pulling from the old, defunct filed that is now all blank since we don't do national counts. I've updated the fieldname in the downloads accordingly (cc @KameronKerger<https://github.com/KameronKerger> and @katherinedm-usds<https://github.com/katherinedm-usds> ) and a PR will be coming shortly with the fix.

**Comment by mattbowen-usds** [comment]
I rebuilt 1.0 and this is corrected now, with the updated column name.
