### ISSUE TITLE
Update footer to match design spec

### ISSUE THREAD

**Issue by katherinedm-usds** [usds/justice40-tool#220]
## Description
We need to update the footer for launch to match design spec. Agency partners should no longer be listed.

## Solution
Design to confirm spec

**Comment by janelien** [comment]
desktop footer

![desktop footer.png](https://images.zenhubusercontent.com/60998bc7b85eebae77bd2048/5b9fb212-e60d-424b-ade1-559525fb1fdc)

**Comment by janelien** [comment]
mobile footer

![mobile footer.png](https://images.zenhubusercontent.com/60998bc7b85eebae77bd2048/8a8f48e2-5ac3-4f73-8e76-2c25bb75cea0)

**Comment by TomNUSDS** [comment]
@janelien Footer design references a Privacy Statement page. Do we need to design this page?

**Comment by janelien** [comment]
I believe @katherinedm-usds shared that the links would be:

Privacy Policy: https://www.whitehouse.gov/privacy/

FOIA: https://www.whitehouse.gov/ceq/foia

**Comment by TomNUSDS** [comment]
Got it. Thanks!

**Comment by TomNUSDS** [comment]
We're also going to need a "Find a contact at USA.gov" link

**Comment by janelien** [comment]
I thought it would just go to https://www.usa.gov/, but it may need a more specific link. 
@katherinedm-usds - what do you think about it linking more specifically to: https://www.usa.gov/pollution (seems to be the most relevant specific link)? or should it just be usa.gov's homepage?

For context, we added it because it's recommended here: https://digital.gov/resources/required-web-content-and-links/

**Comment by katherinedm-usds** [comment]
I think it's ok to use https://www.usa.gov/ that has the overarching guide for different government resources because the question listed is general "Have a question about government services?"

**Comment by TomNUSDS** [comment]
This fix had bugs, so I'm reopening for verification.

**Comment by janelien** [comment]
Small edits: Can we change “Contacts” to be “Contact” and then lower case the ‘i’ in “More information”?
Thanks!
