### ISSUE TITLE
Fix failing build step, part 2: mermaid compilation

### ISSUE THREAD

**Issue by switzersc-usds** [usds/justice40-tool#289]
When merging to main, the compile-mermaid script fails: https://github.com/usds/justice40-tool/actions/runs/936516201

**Comment by TomNUSDS** [comment]
I see this in the github build console:
```
Warning: Unexpected input(s) 'GITHUB_TOKEN', valid inputs are ['ssh-key', 'token', 
'branch', 'folder', 'target-folder', 'commit-message', 'clean', 'clean-exclude', 'dry-run', 
'git-config-name', 'git-config-email', 'repository-name', 'workspace', 'single-commit', 'silent']
Run JamesIves/github-pages-deploy-action@4.1.0
```

I think it's related to the `github_token: ${{ secrets.GITHUB_TOKEN }} ` 
[here in compile_mermaid.yml](https://github.com/usds/justice40-tool/blob/e066f459fa8c2c8e604b60d2056927f4d27a88b2/.github/workflows/compile_mermaid.yml#L51)

But I'd like @NatHillardUSDS to confirm because `GITHUB_TOKEN` is used in [one other place](https://github.com/usds/justice40-tool/blob/e066f459fa8c2c8e604b60d2056927f4d27a88b2/.github/workflows/build_deploy.yml#L85) (Deploy to Github Pages)

**Comment by switzersc-usds** [comment]
Maybe we move this away from Github actions?

**Comment by sverchdotgov** [comment]
This seems to be working now: https://github.com/usds/justice40-tool/actions/workflows/compile_mermaid.yml
