### ISSUE TITLE
Research 2 linguistic isolation indicators

### ISSUE THREAD

**Issue by BethMattern** [usds/justice40-tool#305]
There are 2 linguistic isolation indicators in the list of indicators that Nat provided: "linguistic isolation (percent)" and "Percent of households in linguistic isolation". What is the difference between these two and which one are we using in the score?

**Comment by lucasmbrown-usds** [comment]
Notably, these two currently appear to provide different estimates of isolation, so we should figure out the discrepancy.

**Comment by switzersc-usds** [comment]
Some initial investigation:

EJScreen calculates linguistic isolation like this (as per [their docs](https://www.epa.gov/sites/default/files/2021-04/documents/ejscreen_technical_document.pdf)):

```
lingiso = lingisospanish + lingisoeuro + lingisoasian + lingisoother
pctlingiso = ifelse( hhlds==0,0, lingiso / hhlds)
```
where `hhlds` corresponds to field `C16002.001`.

In our Census ETL, we are calculating linguistic isolation like this:

```
        individual_limited_english_fields = [
            "C16002_004E", # spanish
            "C16002_007E", # euro
            "C16002_010E", # asian / pacific
            "C16002_013E", # other
        ]

      self.df[self.LINGUISTIC_ISOLATION_TOTAL_FIELD_NAME] = self.df[
            individual_limited_english_fields
        ].sum(axis=1, skipna=True)

        self.df[self.LINGUISTIC_ISOLATION_FIELD_NAME] = (
            self.df[self.LINGUISTIC_ISOLATION_TOTAL_FIELD_NAME].astype(float)
            / self.df["C16002_001E"]  
        )
```

I believe both methods are using the same field as the denominator (`C16002.001` aka `C16002_001E`). The most noticeable thing EJScreen does differently is that if the denominator is zero, they set the calculated value to zero. Otherwise as per their docs they do a number of rounding and tie calculations that may cause slight differences between their calucalted values and ours. 

I think the best next step here is to do some analysis of the differences between the outputs of our census etl and the EJScreeen linguistic isolation value and determine if the differences are likely attributed to the above observations or if there is something else going on.

**Comment by lucasmbrown-usds** [comment]
Huh, yeah – so it seems like the formulas are identical (or should be in theory)? 

Would definitely be interesting to do the analysis you suggested. I'm guessing something like 
* Calculate the overall gap between Linguistic Isolation measured in EJSCREEN and Linguistic Isolation measured in CEJST ETL. 
* Find the CBGs with the highest gap between Linguistic Isolation measured in EJSCREEN and Linguistic Isolation measured in CEJST ETL. 
* Open up one or two those CBGs and try to reverse engineer what formula would have led to the output numbers for each of the versions. 

Wdyt?
