### ISSUE TITLE
[SPIKE] As a developer, I want to test the contract between the frontend and backend so that we can make future changes.

### ISSUE THREAD

**Issue by switzersc-usds** [usds/justice40-tool#374]
**Description**
We're pulling a lot of information from various parts of the backend, so let's audit and document that so that we're able to rethink this at a higher level and potentially make architecture changes.

Initially, the main flow of data is from the pbf metadata baked by the backend and read by the frontend, so a test (ideally as a Github Action) that reads the pdb metadata and asserts the fields needed by the frontend are being baked.

The frontend is also using other files from the backend. We should test that these are present so we catch breakages (eg the bug about the 403 on the download file).a.

**Solution**
Documentation of the interface between backend and frontend and the contract of what is necessary. 

Figure out how we want to test this. We considered writing an integration test for the codebase to run on CI/CD for PRs that generates a pbf and reads the properties from the metadata and asserts that they match the columns  required on the frontend. However, right now we have to generate ALL tiles and this is too big for a ci/cd test. We don't know how we would generate just one or two PBFs for the test. MAybe we just want a Github Action that pings the live API to check the data integrity.

**Links to user research or other resources**
None

**Tasks**
- [ ] Spike on how we might test this contract, such as whether we can create just a couple PBFs for use in a CI/CD test
- [ ] Document the needs of the frontend from the backend in a markdown file that gets updated as we move more into an API paradigm

**Definition of "Done"**
- Add documentation or update any diagrams
- Create issues for testing the contract

**Comment by NatHillardUSDS** [comment]
Making spike per convo just now with Jorge + Vim - goal output now is, in addition to tests for the current file structure, a swagger doc describing the interface, and a plan for how to test this longer term. We will also create a separate ticket to diagram the architecture of this setup and how it would live in AWS.

**Comment by vim-usds** [comment]
Adding Nat's eloquent summary from Slack [here](https://usds.slack.com/archives/C0222FBGQ65/p1628097153064000?thread_ts=1628090250.057700&cid=C0222FBGQ65):

> 1. “Phase 1: Known S3 folder structure”: Create postman/newman tests to validate / confirm existing setup
> 2. Create swagger doc for API shape
> 3. Diagram potential future architecture
> 4. “Phase 2: API Gateway REST interface”: Create infra to actually make this API as a REST interface via AWS API gateway
> 5. Update postman tests to use the API instead (should be a small change, as input and output should be same)
> 6. “Phase 3: GraphQL backend” - down the line we may consider adding a GraphQL backend if and when we need to be selective about particular backend responses.
> 
> I would add here that we should leave on the table longer term moving to a proper geospatial DB instead; this would enable us to use a package like Carto to selectively query layer contents and non-geospatial info alike. Obviously a change to our BE infra but might give flexibility if we find we need it.

**Comment by vim-usds** [comment]
@esfoobar-usds and @switzersc-usds,

I think the main way the frontend interacts with the backend is to get the map tiles (PBFs). Let's assume we choose one of the low zoom tiles that are requested with the map first loads. Manual testing is currently _decoding_ the PBFs by:

`curl https://d3jqyw10j8e7p9.cloudfront.net/data-pipeline/data/score/tiles/low/3/1/3.pbf -o d3_313.pbf`

followed by:

`tippecanoe-decode d3_313.pbf 3 1 3 | head -40 | jq`

More specific details can be seen [here](https://github.com/usds/justice40-tool/blob/main/client/VIEW_MAP_DATA.md#decoding-a-pbf-file).

Some quick thoughts on some tests

1. use curl via bash to ensure that tiles are available and accessible (no 403s or CORS issues) on the CDN
2. use curl via bash to ensure cache isn't invalid
3. run above two commands via bash and validate the geo-json shape matches in terms of types and values for each field. This is explained [here](https://github.com/usds/justice40-tool/blob/main/client/VIEW_MAP_DATA.md#geojson-contract-failure)

Haven't explored writing bash scripts too much but maybe this could one approach.

Nat mentioned creating swagger. I think this might work, however since the PBFs may not be a normal HTTP payload, I wonder if some further post-processing via decoding (see above) would be needed to validate the contract. Needs to be investigated if postman/newman can do that.

What are your thoughts?

**Comment by switzersc-usds** [comment]
@esfoobar-usds will post more info on a gdal utility that may help with this

**Comment by esfoobar-usds** [comment]
Here's the utility on the GDAL library to read pbf's metadata:

```
$ ogrinfo -rl https://justice40-data.s3.amazonaws.com/data-pipeline/data/score/tiles/low/5/2/10.pbf
INFO: Open of `https://justice40-data.s3.amazonaws.com/data-pipeline/data/score/tiles/low/5/2/10.pbf'
      using driver `MVT' successful.
```

**Comment by switzersc-usds** [comment]
Next step: Have a dedicated meeting about this
