### ISSUE TITLE
Map sidepanel "Zoom and select" completely covers map on mobile and makes it unusable.

### ISSUE THREAD

**Issue by TomNUSDS** [usds/justice40-tool#566]
**Describe the bug**
On mobile screens, the informational side panel covers the map and makes it unusable.

**To Reproduce**
1. Go to `/en/cejst` on mobile device like an iPhone
Result: 
<img src="https://user-images.githubusercontent.com/74203452/130516816-febf2872-c460-46f8-8bba-05112a640dc3.png" width="300px">

**Expected behavior**
Maybe:
 - move information to under the map on smaller screens.
 - Have the informational side panel have a close blox.

**Comment by switzersc-usds** [comment]
Coping this from a duplicate ticket (#572):

Description
"Zoom in" / CBG info panel should stay below map on mobile phones at TBD breakpoint (regardless of phone orientation)

Current behavior
1. Go to https://d2zjid6n5ja2pt.cloudfront.net/justice40-tool/main/en/ on iPhone 12 and Explore the tool.
2. Observe "Zoom and select a census block group to view data" panel is below the map, as expected.
3. Use multi-touch to zoom to select a CBG and observe panel with "Cumulative Index Score", etc. is still below the map, as expected.
4. Attempt steps 1-3 with iPhone XR, observe panel stays on the side, never goes below map
5. Attempt steps 1-3 with Pixel 3, observe it moves back and forth between landscape and portrait transition

Expected behavior
Panel staying below map regardless of mobile phone orientation is the right tradeoff between simplicity of use and implementation

Screenshots

Smartphone (please complete the following information):

    Device: iPhone XR and Pixel 3 were the ones where panel showed on the side instead of below
    OS: iOS and Android
    Browser: Chrome and Safari
    Version [e.g. 22]

Additional context
Add any other context about the problem here.
