### ISSUE TITLE
As a j40 team member, I want my data pipeline tested so that I know when we generate new versions of the score or available processed data, we'll get good data in the expected format.

### ISSUE THREAD

**Issue by switzersc-usds** [usds/justice40-tool#599]
**Description**
This user story is all about making sure we have adequate testing in place to consider our backend (data pipeline and score generation) production ready!

**Solution**
Generate score, score-post and score-geo on every merge to a PR where the etl/sources and etl/score folder has changes. 

**Describe alternatives you've considered**
We can not have tests and continually live in a state of anxiety and freakouts and fire-fighting when doing new data processing or score experimentation.

**Links to user research or other resources**

**Tasks**

**Definition of "Done"**

**Comment by sverchdotgov** [comment]
Next step is that @esfoobar-usds and I sync on this to figure out holistically how we want to do end to end testing with docker compose.

Some notes so far:

- Tile generation is CPU heavy and that works, so we think compiles will work in github actions.
- This data is public, so rather than generating a small synthetic dataset, we can instead pull out a subset of the data (maybe just one state).
- We can run this just on merges to main, rather than every push to a PR.

**Comment by esfoobar-usds** [comment]
Unfortunately I think we need to run on every merge. I also believe the data should come from S3 mini-fixtures and not from the data sources themselves. We can discuss this afternoon.

**Comment by esfoobar-usds** [comment]
Also, no tile generation needed -- just the score and score-post.

**Comment by sverchdotgov** [comment]
@esfoobar-usds Assigning this to you because I think you are taking over https://github.com/usds/justice40-tool/pull/1134
