### ISSUE TITLE
Update Github Actions to use Poetry as the installer and discard the use of requirements.txt and package caching

### ISSUE THREAD

**Issue by esfoobar-usds** [usds/justice40-tool#651]
**Is your feature request related to a problem? Please describe.**
Right now any new packages added to Poetry require the developer to run a one line command so that Poetry updates `requirements.txt`. This introduces issues for package management and potential issues for missing packages not synced.

**Describe the solution you'd like**
We need to replace the Poetry Github Action package to [Snok/Poetry](https://github.com/snok/install-poetry) and also use [actions/cache](https://github.com/actions/cache) to speed up the CI/CD pipeline.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by sverchdotgov** [comment]
@esfoobar-usds I closed https://github.com/usds/justice40-tool/issues/1100 as a duplicate because I think this is the real solution to that problem.

**Comment by sverchdotgov** [comment]
I notice that the current dockerfile references requirements.txt: https://github.com/usds/justice40-tool/blob/main/data/data-pipeline/Dockerfile#L33

That might also explain why we had that pandas warning turn into an error recently, and only in the docker compose setup, since I recently updated requirements.txt.

@esfoobar-usds Are you okay with me using poetry in the docker setup instead of requirements.txt as part of making this change?

**Comment by esfoobar-usds** [comment]
Yes, we can install and run poetry on Dockerfile.

[I have this example](https://github.com/fromzeroedu/quart-postgres-boilerplate/blob/main/Dockerfile#L17-L27) from one of my bootstrap projects.
