### ISSUE TITLE
[SPIKE] Investigate (and ideally implement) front end error monitoring

### ISSUE THREAD

**Issue by switzersc-usds** [usds/justice40-tool#679]
Let's just keep this scoped to JS console errors. We have uptime monitoring and we're working on automated workflow/feature tests with Cypress/Cucumber. 

Tasks:

-[] Ask GP if they have a tool for this we can use out of the box
-[] Research available free and open source solutions
-[] Can we use our DAP analytics for this?
-[] Can we do this (at least in part) as part of CI/CD?
-[] Ask Lisa C if USDS/OMB has anything available for use (eg Sentry)

Output: New Github issues for implementation of monitoring

**Comment by sverchdotgov** [comment]
I can see a couple categories here:

1. Simple ping uptime checks.
2. External workflow checks.
3. Client side javascript error reporting.

I think those are in order of how important they are.

The ping checks are the last backstop for unplanned outages, and will make sure someone finds out if the site is down, even if the other server side monitoring is broken.

The workflow checks can be written to automatically verify that certain workflows are functioning from an external perspective (e.g. logins still work).

The client side javascript libraries could be useful, but seem more likely to catch coding errors than unplanned outages, which other parts of the development flow should be set up to catch as well. Not that it wouldn't help, it just seems less critical. The one exception I can think of is if the client is reaching out directly to unmonitored third party systems that you don't trust, that might be more worth adding, but I'd also say that thoughtfully crafted workflow checks can handle this.

What ability do you have to pay for external services? Looks like AWS has a feature for doing ping checks and workflow monitors if that's the only thing you have access to: https://aws.amazon.com/blogs/aws/new-use-cloudwatch-synthetics-to-monitor-sites-api-endpoints-web-workflows-and-more/

**Comment by switzersc-usds** [comment]
Awesome, thanks for this, @sverchdotgov! I think categories 1 and 2 are most critical right now. Let's talk through what the client is doing and what AWS features we may have access to when we meet.

**Comment by switzersc-usds** [comment]
Next steps: 
- we're adding analytics to help with monitoring 
- we're setting up a Github Action to run on a regular schedule to check uptime of the site and email our support email if the site is down

**Comment by sverchdotgov** [comment]
@switzersc-usds So it turns out emailing from github actions is a bit complicated because you need to add mail server credentials. They all look pretty similar to this: https://github.com/marketplace/actions/send-email-action With gov emails I'm not sure how to do that.

Some options:

1. Use this instead, and just create an issue if something fails: https://github.com/marketplace/actions/create-an-issue. You'll need to add a repository key.
2. Do something more complicated involving AWS synthetics and trying to figure out how to set up alerting for that.

If the site had more parts to it, I would be thinking more about fancy things with the AWS synthetics, but from what you described, just having analytics might be enough.

The value of doing the automatic issue creation would be to have a log of issues that you could use as data for trying to find the root cause of something intermittent, but if it's just a simple ping check failing on static content I don't think it would give you anything really actionable (because it's just S3 and a CDN).

Honestly, given all this, I'd say analytics is the most important thing, and if the situation ever changes to the point where the concept of "on call" is more of a thing, that's when I'd revisit the other monitoring. From what you said it sounded like you're not set up to actually "page" people right now anyway.

**Comment by switzersc-usds** [comment]
Hmmm.... How about a slack notification instead of an email?

**Comment by vim-usds** [comment]
@switzersc-usds 

Spoke with Lisa C, and got the following info. They are using the free version of Sentry. That free account is tied to her email address. 

If we feel the free version can work for now ( which I think it can), there are two ways we could proceed:
1. create a sentry account with my OMB email address
2. use an mailing list (existing or new one with just engineers) 

If in agreement, do you have a preference for 1 vs 2? If 2, should it be a new mailing list or an existing one? I'm wondering if it's valuable to have the entire team getting the Sentry notifications? I'm leaning no.

As a corollary, some food for thought that was also offered:

1. if, in the event we need to migrate to a paid plan, do we know if our agency will cover that? It seems that this question will come up if we ask OMB to pay. Although important to plan for the future, in my mind this concern is less important for me and I am taking the approach of "let's cross that bridge when we get there".
2. Second corollary, do we have an agreement in place for geoplatform to support our hosting needs? If so, how long is that agreement valid for?

**Comment by vim-usds** [comment]
https://sentry.io/for/react/

Also a note to add a Error Boundary or a Gatsby way to do that.

**Comment by vim-usds** [comment]
Waiting to get the PR approved by Lisa on creating the j40-engineering mailing list
