### ISSUE TITLE
Integrate versioning into UI

### ISSUE THREAD

**Issue by vim-usds** [usds/justice40-tool#710]
![Screen Shot 2021-09-16 at 2.49.08 PM.png](https://images.zenhubusercontent.com/60d4d92c1bf5e498d6e808ba/e966aba9-e05a-4346-b5a6-a0520bcb7360)![Screen Shot 2021-09-16 at 2.48.37 PM.png](https://images.zenhubusercontent.com/60d4d92c1bf5e498d6e808ba/f54a2218-6246-4c82-be56-9530c25277c6)

**Comment by switzersc-usds** [comment]
Note that mockups have "v.02" but we want to use "v0.1"

**Comment by vim-usds** [comment]
QA review here please:
http://usds-geoplatform-justice40-website.s3-website-us-east-1.amazonaws.com/justice40-tool/6f237f/en/methodology

**Comment by KameronKerger** [comment]
Three nits @vim-usds 
1. in the blue box can we update the text from "draft v0.1 of the list communities of focus" to "draft v0.1 of the list **of** communities of focus"
2. the button in the blue box "Download package" instead of "Download packet"
3. on the map page, can we add a little more space between the Community of focus and the version number... maybe 8 - 10ish pixels.

**Comment by vim-usds** [comment]
@KameronKerger - Awesome feedback, here's the updated staging URL for QA:

http://usds-geoplatform-justice40-website.s3-website-us-east-1.amazonaws.com/justice40-tool/868c95/en/cejst/#3/32.47/-86.5

**Comment by KameronKerger** [comment]
looks good to me, thanks @vim-usds
