### ISSUE TITLE
Include X-Frame-Options header in HTTP responses

### ISSUE THREAD

**Issue by switzersc-usds** [usds/justice40-tool#712]
This came out of a security scan we did last week. Adding this header to HTTP responses will protect against 'ClickJacking' attacks. Needed on all pages. See scan results posted in our incidents channel.

**Comment by vim-usds** [comment]
Hi @switzersc-usds,

Adding a Cloudfront function to add the appropriate response Headers:
- https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/example-function-add-security-headers.html

When downloading OWASP ZAP tool, was unable to open due to suspicious malware. is this right place to download the tool? - https://www.zaproxy.org/download/

Can we either set up a time to install this locally or if you can re-run to see if you are still getting the X-frame error? Thx.
