### ISSUE TITLE
[SPIKE] Load census block group geographic boundaries for the 4 territories

### ISSUE THREAD

**Issue by BethMattern** [usds/justice40-tool#724]
We need the geometries for the 4 territories and they need to be on the geojson and score CSV. We need to figure out what the source data is for this. We should ping Geoplatform to see if they can help.

**Comment by switzersc-usds** [comment]
It is straightforward to add the territories to the census shape file ETL. 
Then score generation will try to left join territory boundaries with other data and we'll get a bunch of NaNs.
Additionally, because the map is driven by the score CSV, if there is no data for those territories they might not even appear. 

Thoughts:
* We can have an exclude list and for any ETLs that would break on the left join with territory FIPS codes, we can skip those. E.g. ACS, which stopped collecting data for territories in 2010. 
* Then we can add the territories back during Score ETL Post so that we bake the tiles and show as "Not enough data" for the score value. Maybe show as a striped pattern or gray.

**Comment by switzersc-usds** [comment]
Created #804 and #805 as a result of this spike and convo.
