### ISSUE TITLE
[SPIKE] Figure out what logging and alerting capabilities we have and want to set up

### ISSUE THREAD

**Issue by switzersc-usds** [usds/justice40-tool#822]
Output should be new issues that we can prioritize and documentation.

We already have Sentry and there is probably some overlap with that. We should document what Sentry is alerting us to and when. 

We should also turn on Cloudfront logging and monitor that. Additionally, we want to look into CI/CD dependency monitoring and make a plan for this (eg Github Actions checking for the data source on S3 or on external site). 

Resources:

- https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/AccessLogs.html

**Comment by vim-usds** [comment]
Tasks

- [x] create separate bucket for access logs
- [x] Email to Zivaro on permissions
- [ ] connect CDN to S3
- [ ] GHA to remove logs as a cron

need clarification on "Github Actions checking for the data source on S3 or on external site"

**Comment by vim-usds** [comment]
## Managing access logs on Cloudfront
In order to set up access (aka standard logs) on our web Cloudfront (or any Cloudfront for that matter), we need a dedicated S3 instance. This has been created and is called `j40-website-access-logs`.

The Cloudfront instance is pointed to this S3 and logs show up ( i think). S3 doesn't automatically remove logs. We can manage the logs by something they call _Lifecycle rules_.

### Lifecycle rules
The Lifecycle rules allows us to 
1. move the logs to cheaper tiers of S3
2. expire (and therefore delete/remove) objects after a certain amount of time
3. both

### Move logs to cheaper tiers of S3
Here are the various [tiers](https://aws.amazon.com/s3/pricing/)
- Standard S3 (what we have now, fastest access) has a storage cost of .23/GB
- Standard Infrequent (ms access time) costs .0125/GB
- Glacier S3  (1 min to 12 hours access time) costs .004/GB
- Glacier Deep Archive S3 - (access once / twice per year within 12 hours) costs .00099/GB

### Expire objects
We can also simply expire them after certain number of days.

### Questions
_What do we want from these logs? Should we keep them forever? Do we need the entire history of the app's access logs?_

Some of these questions will help drive our strategy for choose the appropriate lifecycle method.

**Comment by switzersc-usds** [comment]
Thanks for this great write-up! 

So first thing, I want to clarify what we mean by access logs. I usually use this to refer to developer or console access to infrastructure (eg S3 or Cloudfront), not HTTP/S traffic / public access to the site or data folders. Is that accurate, or does access mean public HTTP/S traffic? Or does AWS treat these as the same?

On retention for traffic logs, I don't think we have a use case for storage longer than a year, although I imagine we'd want to watch trends over multiple years, but that can be done at a less granular level than logs. This is more for monitoring and understanding trends for product strategy and feature development, rather than security (as we don't have PII or sensitive information). Since that's the main purpose, you're right, we can get this through Google Analytics / DAP / etc for the website, but not for the data folders. We do want to also track traffic to the S3 data folders so we understand when and how external parties are using our data. Maybe this is covered under the access logs? If not, we should definitely set something up to monitor this and understand trends. 

For developer / console access to our infrastructure, we do want to store that and monitor for security purposes, but again, this system does not store sensitive information and pretty much all data and files are available via public HTTP/S access anyway. We would just want to see, for example, if something changed about a bucket/distro config that caused a problem and who changed it when. In this case, probably deleting after 30 days is fine.
