### ISSUE TITLE
Update export file to include all indicators used in methodology

### ISSUE THREAD

**Issue by BethMattern** [usds/justice40-tool#857]
Expected building loss rate (Natural Hazards Risk Index)
Expected building loss rate (Natural Hazards Risk Index) (percentile)
Expected agricultural loss rate (Natural Hazards Risk Index)
Expected agricultural loss rate (Natural Hazards Risk Index) (percentile)
Expected population loss rate (Natural Hazards Risk Index)
Expected population loss rate (Natural Hazards Risk Index) (percentile)
Add Expected annual loss rate 
Add Expected annual loss rate (percentile)
Add Proximity to RMP sites
Add Proximity to RMP sites (percentile)
Add Proximity to NPL sites
Add Proximity to NPL sites (percentile)
Add Unemployment
Add Unemployment (percentile)
Add Linguistic isolation
Add Linguistic isolation (percentile)
Remove Life expectancy (years)
Remove Life expectancy (years) (percentile)
Add Percent of individuals < 200% Federal Poverty Line
Add Percent of individuals < 200% Federal Poverty Line (percentile)

**Comment by vim-usds** [comment]
Hi @BethMattern , in order to add indicators I believe they have to exist in the [usa.csv](https://justice40-data.s3.amazonaws.com/data-pipeline/data/score/csv/full/usa.csv) file. I am using the following emoji to indicate if they exist or not

❌  - column name doesn't exists
✅  - column name does exists

For the ones that don't exist, I'm taking a stab at which one you may have meant:

### The following cases I found what I believe is the column header / indicator you intended
~Add Proximity to RMP sites~ ❌ 
Add Proximity to Risk Management Plan (RMP) facilities ✅ 
~Add Proximity to RMP sites (percentile)~ ❌ 
Add Proximity to Risk Management Plan (RMP) facilities (percentile) ✅ 

Add Proximity to NPL sites ✅ 
Add Proximity to NPL sites (percentile) ✅ 

~Add Unemployment~ ❌ 
~Add Unemployment (percentile)~ ❌ 
Add Unemployed civilians ✅ 
Add Unemployed civilians (percentile) ✅ 

### In this case I'm not sure which ones to use?
~Add Linguistic isolation~ ❌ 
~Add Linguistic isolation (percentile)~ ❌ 

Linguistic isolation (percent) ✅ ❓ 
Percent of households in linguistic isolation ✅ ❓ 
Linguistic isolation (percent) (percentile) ✅ ❓ 
Percent of households in linguistic isolation (percentile) ✅ ❓ 

Thanks for clarifying!

**Comment by BethMattern** [comment]
@lucasmbrown-usds i feel like you should answer @vim-usds question above to make sure for sure we're pulling in the same values that Score L uses.

**Comment by vim-usds** [comment]
thanks @lucasmbrown-usds !

**Comment by switzersc-usds** [comment]
Closing as now covered by #856
