### ISSUE TITLE
Convert county mapping to use tracts, not CBGs

### ISSUE THREAD

**Issue by switzersc-usds** [usds/justice40-tool#874]
We should look into whether we can use Geocorr (which we use for other mapping earlier in the process). Maybe we  don't want to do that though in case we drop Geocorr in the future. Whoever takes this should figure this out by leading the covnersation and understanding what we get from Geocorr and when.

**Comment by lucasmbrown-usds** [comment]
Yeah we may want to remove the `etl_score_post.py` part that adds county information, since this comes from geocorr earlier in the process. 

This is where we currently add county: https://github.com/usds/justice40-tool/blob/main/data/data-pipeline/data_pipeline/etl/sources/census_acs_median_income/etl.py#L94 

And it is saved as part of the output file for that: https://github.com/usds/justice40-tool/blob/main/data/data-pipeline/data_pipeline/etl/sources/census_acs_median_income/etl.py#L51. 

I would vote we move forward using that field instead of the `etl_score_post` step. I don't think we'll remove the Median Income data anytime soon (it's part of Def L) and if we do, we can always keep just the geocorr part.
