### ISSUE TITLE
Turn Cloudfront/S3 logs on

### ISSUE THREAD

**Issue by switzersc-usds** [usds/justice40-tool#912]
Refer to #822 for more info.

Basically, for now we want to turn logs on for HTTP traffic to our resources so that we can monitor usage. We will set up monitoring/parsing etc later.

**Comment by vim-usds** [comment]
@sverchdotgov - if you get AWS access and if you have time, can you look into this? Let's chat if you have the bandwidth

Thanks!

**Comment by sverchdotgov** [comment]
Yup, happy to chase this @vim-usds.

**Comment by sverchdotgov** [comment]
@vim-usds Have you been configuring this via the console so far?

I'm hesitant to add another dependency, but in this case I'd recommend we use something like https://registry.terraform.io/modules/tmknom/s3-access-log/aws/latest for this. You can see in the source [here](https://github.com/tmknom/terraform-aws-s3-access-log/blob/master/main.tf) how much knowledge is built into this module that we wouldn't have to maintain if we used it. I believe that can address your comment [here](https://github.com/usds/justice40-tool/issues/822#issuecomment-965867356) about lifecycle rules.

**Comment by sverchdotgov** [comment]
Decision we made in our discussion:

Top priority is getting logs enabled and going to an s3 bucket. The lifecycle questions can be done later.

We should use terraform only if it will actually make things faster, since we want to add minimal churn for launch. So that will probably come when we talk about the lifecycle questions.

Eventually, having all configuration in terraform might be nice, but that's also a longer term question.

**Comment by sverchdotgov** [comment]
#### Current Status

The `j40-website-access-logs` bucket currently exists at https://s3.console.aws.amazon.com/s3/buckets/j40-website-access-logs?region=us-west-2&tab=objects.

I don't have permissions to create an access key, so I'm asking for that now.

#### Standard Vs Real Time Logs

From https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/AccessLogs.html:

> You can configure CloudFront to create log files that contain detailed information about every user request that CloudFront receives. These are called standard logs, also known as access logs.

> CloudFront also offers real-time logs, which give you information about requests made to a distribution in real time (logs are delivered within seconds of receiving the requests). You can use real-time logs to monitor, analyze, and take action based on content delivery performance.

So I think we want standard logs, because real time logs seem to be for the live automation use case (i.e. having software that can automatically respond to performance measurements from the CDN) which we don't need since this site is being served from s3, not from infrastructure that we have to worry about scaling ourselves.

#### Required Configuration For S3 Logs Bucket

I'm looking at https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/AccessLogs.html#AccessLogsBucketAndFileOwnership now to figure out what permissions I need to set so that cloudfront can log to the s3 bucket.

> Your AWS account must have the following permissions for the bucket that you specify for log files:
> 
> - The S3 access control list (ACL) for the bucket must grant you FULL_CONTROL. If you're the bucket owner, your account has this permission by default. If you're not, the bucket owner must update the ACL for the bucket.
> - s3:GetBucketAcl
> - s3:PutBucketAcl

I think this is the permission that I need to have to set this up, not the permissions that cloudfront needs, since it says "your aws account". I think I'll find out whether I have these permissions when I try to set this up.

Oh wait:

> When you create or update a distribution and enable logging, CloudFront uses these permissions to update the ACL for the bucket to give the awslogsdelivery account FULL_CONTROL permission. The awslogsdelivery account writes log files to the bucket. If your account doesn't have the required permissions to update the ACL, creating or updating the distribution will fail.

So it sounds like cloudfront will use my permissions to automatically grant itself the permissions it needs. So let me check that I have that permission on the bucket, and then everything else should work.

#### Checking Required Permissions

I'm looking at https://docs.aws.amazon.com/AmazonS3/latest/userguide/acl-overview.html#permissions and I see this set of permissions: `READ`, `WRITE`, `READ_ACP`, `WRITE_ACP` and `FULL_CONTROL`. I think I want `FULL_CONTROL`, but the console doesn't show that anywhere, and has every box checked for the account owner so I'm going to move on for now.

#### Cloudfront Logging Configuration

I'm going to this page: https://console.aws.amazon.com/cloudfront/v3/home?region=us-east-1#/logs/standard/E27WCOZZ03KIBX to change the logs.

On that page, everything is "Disabled" except for "Distribution Status" under real time logs. I'm not sure what that means and why it's enabled. That might just mean "is the corresponding cloudfront distribution for this log configuration enabled".

Standard logs are currently disabled, and that's the one we want.

**Comment by sverchdotgov** [comment]
Submitted request for permission to generate access keys.

**Comment by sverchdotgov** [comment]
![Screen Shot 2021-12-09 at 2 46 51 PM](https://user-images.githubusercontent.com/25348713/145465485-5a6f0ea3-17c9-47f2-956f-46ecb860ab54.png)

**Comment by sverchdotgov** [comment]
![Screen Shot 2021-12-09 at 2 50 26 PM](https://user-images.githubusercontent.com/25348713/145465884-78493410-e90e-4283-8e4c-dfd6e2ae3730.png)

**Comment by sverchdotgov** [comment]
Going to wait until it no longer says "deploying" to see if logs show up.

**Comment by sverchdotgov** [comment]
![Screen Shot 2021-12-09 at 3 03 36 PM](https://user-images.githubusercontent.com/25348713/145467718-3c8da386-181a-43dd-aa22-ac3cc81effce.png)

Going to turn on bucket versioning.

**Comment by switzersc-usds** [comment]
W00t! Thanks @sverchdotgov ! Marking this as closed!

**Comment by sverchdotgov** [comment]
Reopening this because we want to add access logs for all our distributions.

**Comment by sverchdotgov** [comment]
Ok, now this is done for all distributions.
