### ISSUE TITLE
FE dependabot failures

### ISSUE THREAD

**Issue by vim-usds** [usds/justice40-tool#962]

**Comment by vim-usds** [comment]
most are in dev packages with will not be running during prod

**Comment by sverchdotgov** [comment]
Looking into this now. Seems like we are running this version of gatsby: https://github.com/gatsbyjs/gatsby/releases/tag/gatsby%403.14.0

From those release notes:

> We will keep publishing patches for 3.14.x with hotfixes until 4.0.0 stable is published and at least several weeks after.

`4.0.0` was released in October, so it's possible they're not updating this anymore. There are a few dependency issues from gatsby, which I would have expected to be fixed upstream. I'm going to try updating to the latest and see what happens.

**Comment by sverchdotgov** [comment]
Running `npm install gatsby@latest`.

**Comment by sverchdotgov** [comment]
Actually, now that I know how to do this, I can confirm that you're right that it's dev-only:

```
% npm audit --prod

                       === npm audit security report ===

found 0 vulnerabilities
 in 274 scanned packages
```

The deploy action even has a check for it: https://github.com/usds/justice40-tool/blob/main/.github/workflows/deploy_staging.yml#L51 https://github.com/usds/justice40-tool/blob/main/.github/workflows/deploy_main.yml#L52

I created https://github.com/usds/justice40-tool/pull/1041, because I think this qualifies as over-alerting.

**Comment by sverchdotgov** [comment]
I think we can call this done now.

**Comment by sverchdotgov** [comment]
New dependabot config is merged to only alert on prod security issues.
